### ISSUE TITLE
Problems importing Dreamcast CHD

### ISSUE THREAD

**Issue by ColetteDiskette** [alucryd/oxyromon#162]
I have a dump of 4 Wheel Thunder for Dreamcast that matches Redump checksums when importing them as BIN/CUE. If I convert them to CHD (via oxyromon,) move them elsewhere, purge, then try to import the CHD, I get:

```
Processing "4 Wheel Thunder (USA).chd"
CUE file found
Matches "4 Wheel Thunder (USA).cue"
Extracting "4 Wheel Thunder (USA).chd"
Error: SimpleError { err: "Failed to delete \"/tmp/.tmpncVLh7/.4 Wheel Thunder (USA).cue\", No such file or directory (os error 2)" }
```

Here is the output of `oxyromon info`:

```
Version: 0.19.0

Dependencies:
  7-zip: found (17.05)
  bchunk: found (1.2.2)
  chdman: found (0.270)
  ctrtool: not found
  dolphin: found (unknown)
  isoinfo: found (3.02a09)
  maxcso: found (1.13.0)
  nsz: not found
  wit: not found

Systems: 240
Games: 248921
Roms: 1238624
```

I'm on Arch Linux.
