### ISSUE TITLE
Quirk with MAME games that require BIOS files

### ISSUE THREAD

**Issue by ColetteDiskette** [alucryd/oxyromon#177]
As it stands right now, it seems oxyromon won't consider a MAME game complete unless all the BIOS files are also there. Here's what I mean:

Say I have `cotton2.zip`. It has all the files expected to be in `cotton2.zip`:

```
mpr20116.1
mpr20117.2
mpr20118.3
mpr20119.4
mpr20120.5
mpr20121.6
mpr20122.7
mpr20123.8
```

I do `oxyromon import-roms cotton2.zip`. It will detect all of those ROM files and place them in a folder called `cotton2`. If I do `oxyromon convert-roms -s "MAME" -f ZIP`, it will not make a ZIP of that game.

What oxyromon seems to want to do is also have the contents of `stvbios.zip` and `segabill.zip` since those are dependencies for `cotton2`. If I then import those two BIOS ZIPs, they will import as `stvbios.zip` and `segabill.zip`. I then have to copy those files back over to the directory I'm importing from and import them AGAIN. At this point, oxyromon will ask me which game to assign each file in them to, and I can assign them to `cotton2`. If I do that, then do `oxyromon convert-roms -s "MAME" -f ZIP` again, it will make a new `cotton2.zip` that has the contents of the normal `cotton2.zip`, `stvbios.zip`, and `segabill.zip`.

Here's the problem with this. MAME (at least not the libretro core) doesn't give a crap about BIOS files that are in the same ZIP as the game. They will be ignored. That `cotton2.zip` will not launch unless I have `stvbios.zip` and `segabill.zip` alongside it, so by doing things the way oxyromon seems to want them, I'm having to duplicate BIOS files for no good reason.

I like a non-merged set, and doing `oxyromon rebuild-roms -m NON_MERGED -a` doesn't change this at all (as I would expect it wouldn't since I can't think of a merging style that puts the BIOS files in; not even merged does this.)

### `oxyromon info` output:
```
Version: 0.20.1

Dependencies:
  7-zip: found (24.09)
  bchunk: not found
  chdman: found (0.273)
  ctrtool: not found
  dolphin-tool: found (unknown)
  flips: not found
  maxcso: found (1.13.0)
  nsz: not found
  wit: not found
  xdelta3: not found

Systems: 1
Games: 47530
Roms: 347334
```
