### ISSUE TITLE
Issue importing IBM Redump DAT

### ISSUE THREAD

**Issue by ColetteDiskette** [alucryd/oxyromon#188]
Back on getting things sorted again on my end (but still not back on my MAME mess because logistics) I'm having issues importing `IBM - PC compatible - Datfile (51628) (2025-04-13 00-03-04).dat` either manually downloaded from Redump or through oxyromon.

What it does is start the import, get to somewhere around 51600 (plus or minus maybe 30, variably) then hang. I've tried it multiple times, tried deleting the database in `~/.local/share/oxyromon`, and even tried letting it sit with one CPU thread pegged at 100% (on my Ryzen 7 5700X) for over an hour and 15 minutes. All I can do is hit Ctrl+C to cancel the import here. Other DATs import fine, so I suspect perhaps the massive size of this DAT is causing an issue.

`oxyromon info` output:
```
Version: 0.20.2

Dependencies:
  7-zip: found (24.09)
  bchunk: not found
  chdman: found (0.276)
  ctrtool: not found
  dolphin-tool: found (unknown)
  flips: not found
  maxcso: found (1.13.0)
  nsz: not found
  wit: not found
  xdelta3: not found

Systems: 0
Games: 0
Roms: 0
```

(The Systems/Games/Roms are 0 because of me deleting the database.)

Also, in case it somehow matters: Arch Linux, Linux 6.13.8-zen1-1-zen, KDE Plasma 6.3.4 (X11 session), Ryzen 7 5700X, Radeon RX 7600, 64GB RAM.

I should be getting back to the MAME business soonish and I can finally check that out. Feel bad for taking so long! Also, thanks! 😅
